Running script...

paths found for loading
Spec_twofold_Inderfold_0.json
SVM done 0.945010183299389
Lda done 0.9409368635437881
DT done 0.8920570264765784
RF done 0.9837067209775967
fold 0 completet
SVM done 0.636
Lda done 0.546
DT done 0.666
RF done 0.69
fold 1 completet
Traceback (most recent call last):
  File "Classifier_experimentOne_isUsable/Classifier_test.py", line 253, in <module>
    CV.two_layes(type="spectrograms", EXP_name="Spec_twofold")
  File "Classifier_experimentOne_isUsable/Classifier_test.py", line 149, in two_layes
    Innerresult=self.test(folds=[n],classifyers=classifyers, type=type, logname=logname)
  File "Classifier_experimentOne_isUsable/Classifier_test.py", line 104, in test
    AC_matrix.loc[n,C]=self.predict_svm(x_train,y_train,x_test,y_test)
  File "Classifier_experimentOne_isUsable/Classifier_test.py", line 199, in predict_svm
    m_svm.fit(x, y)
  File "/zhome/87/9/127623/Fagprojekt/Fagprojekt2020/classifier-env/lib/python3.8/site-packages/sklearn/svm/_base.py", line 164, in fit
    y = self._validate_targets(y)
  File "/zhome/87/9/127623/Fagprojekt/Fagprojekt2020/classifier-env/lib/python3.8/site-packages/sklearn/svm/_base.py", line 549, in _validate_targets
    raise ValueError(
ValueError: The number of classes has to be greater than one; got 1 class
